### PR TITLE
monomorphize new unifier

### PR DESCRIPTION
**Pull request by dwightguth**
### Scope:

This PR removes use of `UnifierT` from NewUnifier.hs and its callers, replacing it where needed with `LogicT Simplifier`. This also ends up triggering monomorphization of a large number of functions in the Kore.Rewrite package.

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by jberthold** [comment]
I guess `MonadUnify` could also be removed then? (leading to the removal of [Kore.Unification.Unify](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Unification/Unify.hs)  which would only re-export `Logic` functions and `InternalVariable`)

**Review by jberthold — COMMENTED** [review]
The problems with the test setup stem from the type changes in `unificationProcedure` and `transitionRule`.

About [line 247 in kore/test/Test/Kore/Unification/Unifier.hs](https://github.com/runtimeverification/haskell-backend/pull/3241/files#diff-514df8bc553b95c652b5106aed00e48ffcfb3eeccae12f141b7ef36ffde4d32c), your type change of `unificationProcedure` now requires using `observeAllT` instead of `runUnifierT Not.notSimplifier`
```
-                unificationProcedure
-                    SideCondition.topTODO
-                    term1
-                    term2
-                    & Monad.Unify.runUnifierT Not.notSimplifier
-                    & runSimplifier mockEnv
-                    & runNoSMT
+                runNoSMT
+                    . runSimplifier mockEnv
+                    . Monad.Unify.observeAllT
+                    $ unificationProcedure
+                        SideCondition.topTODO
+                        term1
+                        term2
```
The other two errors about `AllPathIdentity` are more subtle, the test needs to be rewritten (as you mentioned on slack, an _actual_ simplifier needs to be used now) so we cannot use the `Test.Terse` combinators (whose value is ... unclear IMHO). Replacing the combinators in `MockAllPaths` would not be too hard.

How does the performance look for this PR?

**Comment by dwightguth** [comment]
> I guess `MonadUnify` could also be removed then? (leading to the removal of [Kore.Unification.Unify](https://github.com/runtimeverification/haskell-backend/blob/master/kore/src/Kore/Unification/Unify.hs) which would only re-export `Logic` functions and `InternalVariable`)

MonadUnify and UnifierT are still used by the old unifier, which is still used by And and Equals simplification. I tried removing these usages at the time I developed the new unifier, and it proved difficult, so I gave up.

**Review by jberthold — APPROVED** [review]
LGTM. Memory profile looks like this might accelerate execution :crossed_fingers:

**Review by ana-pantilie — APPROVED** [review]

**Pull request merged**
