### PR TITLE
Remove eventlog2threadscope dependency

### LINKED ISSUE #3480: Try removing pipes-sqlite-simple dependency
This package is not currently maintained, and is not on Stackage.

### PR DESCRIPTION
**Pull request by treeowl**
We only use this for `kore-prof`, which doesn't actually do anything related to Kore. It should therefore be in its own repository.

Closes #3480

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by treeowl** [comment]
I've tentatively moved the removed code to https://github.com/runtimeverification/prof-util. The name I chose is surely terrible, but I don't know what you want to call this stuff. I can drag the dependencies into that repository as well. I have not as yet made any effort to get anything there to compile; it's just to have a place for these things.

**Comment by jberthold** [comment]
`happy` is making us unhappy today: https://github.com/haskell/happy/issues/250 
The github runner setup calls `cabal update` which pulls in a bad version uploaded a few hours ago.

**Comment by treeowl** [comment]
It looks like the new version has now been deprecated, so I'll try again.

**Comment by treeowl** [comment]
Oh, I guess that'll have to wait for integration tests to finish. Whatever....

**Review by ana-pantilie — APPROVED** [review]

**Pull request merged**
