### PR TITLE
Strict hash caching

### PR DESCRIPTION
**Pull request by treeowl**
Strict hash caching

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by jberthold** [comment]
Looked at the measurements... unfortunately this is slower than master . :disappointed: So it is the other PR that we want, I guess.

**Comment by treeowl** [comment]
@jberthold There's also a very mysterious error in the integration tests. This is all very odd. Are there any actually lazy operations other than `fromConcrete`?

**Comment by treeowl** [comment]
Or maybe there's something else lazy and the hash never gets taken? Very odd.

**Comment by jberthold** [comment]
> @jberthold There's also a very mysterious error in the integration tests. This is all very odd. Are there any actually lazy operations other than `fromConcrete`?

That error is actually a flake - sometimes the SMT solver cannot keep up (or something else goes wrong) and it sends this `Push canceled` response, making the test fail. A re-run will show whether or not this is the problem here.

> Or maybe there's something else lazy and the hash never gets taken? Very odd.

I could imagine there are many `TermLike` that never make it into the simplifier cache - in the strict version we will compute their hashes unnecessarily. Just a guess - but whatever the reason,  the numbers speak clearly.

**Comment by treeowl** [comment]
Okay, we won't do it then.

**Pull request closed without merging**
