### PR TITLE
Streamline addElementDisjoint

### PR DESCRIPTION
**Pull request by treeowl**
`addToMapDisjoint` uses an unexported helper function `addElementDisjoint` to insert elements into a `HashMap`. For some reason, these were written to accumulate a (reversed) list of the elements inserted along with the actual `HashMap`, and then throw the list away. This was both wasteful and confusing. Stop doing it.

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by treeowl** [comment]
I can't begin to guess how this could change any results. Is there something really flaky in the Nix integration tests, or am I missing something?

**Comment by jberthold** [comment]
The failure in `test/Cabal` is a known flake: This error 

> Cannot generate terms for SortActualSort (SortActual {sortActualName = InternedId {getInternedId = "mapSort", internedIdLocation = AstLocationTest}, sortActualSorts = []})

comes from a weakness of our test data generators. (there is a ticket in the backlog to consolidate them)
I have restarted the cabal build job

**Review by jberthold — APPROVED** [review]
Good catch!
I dug up git history but could not figure out what this list was meant to support originally...

**Comment by jberthold** [comment]
IDK why the auto-merger does not actually _merge_ this (it only updates the branch in preparation to do so). Possibly because this is from a fork instead of a branch in our repository.

**Pull request merged**
