### PR TITLE
Gather more efficiently

### PR DESCRIPTION
**Pull request by treeowl**
`Control.Monad.Logic.msplit` is well known to be slow. See, most notably, the
[Reflection without Remorse](https://okmij.org/ftp/Haskell/zseq.pdf) paper. Use a custom variant of `MonadLogic` with a `gather` method to implement `gather` more efficiently.

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by treeowl** [comment]
Since the `logict-sequence` idea seems to be stalled, we might as well see if this much more conservative change is worthwhile.

**Comment by treeowl** [comment]
No difference. I guess `gather` isn't producing long lists in these tests. Are there realistic situations where it might?

**Comment by ana-pantilie** [comment]
@ehildenb suggested crafting an example which branches a lot. We can find out if this PR actually has an impact in such a situation.

**Comment by ehildenb** [comment]
[example.zip](https://github.com/runtimeverification/haskell-backend/files/10115108/example.zip)

This example contains two files: `test.k` and `inp.pgm`. You can run it with:

```
kompile test.k --backend haskell --main-module TEST --syntax-module TEST
krun --depth 1 inp.pgm --output kore --parser cat --term --no-expand-macros
```

And it causes a branch of size 1010 (which should trigger constructing a multior of size 1010).

You can make the branching bigger or larger by adding more/less rules in `test.k`, and rekompiling and rerunning.

Maybe this helps us to understand the performance implications of `gather` changes? Not sure, because I don't know if this example will actually exercise that case.

**Comment by treeowl** [comment]
The example @ehildenb unfortunately only produced `gather`s of size 1. Closing this for now, as we don't know of a test case where it makes a difference.

**Pull request closed without merging**
