### PR TITLE
Remove internal implementation of symbolic Set.difference and Set.in

### LINKED ISSUE #2928: Haskell backend loops on simple proof
Given K version (v5.2.21 with only updates to pyk library, should not affect this bug) and kore-exec version:

```
+ kompile --version
K version:    v5.2.21-17-g60eaf47005-dirty
Build date:   Wed Dec 01 21:25:44 UTC 2021
+ kore-exec --version
Kore version 0.58.0.0
```

we have an infinite loop (or seemingly), and it uses a lot of memory (OOMs my 96GB machine) on this specification:

```
requires "domains.md"

module TEST
    imports INT
    imports SET
    imports BOOL 

    configuration <k> $PGM:Foo </k>

    syntax Foo ::= run ( Set ) | done ( Set )
 // -----------------------------------------
    rule <k> run(S) => done(S) ... </k>

    syntax Int ::= f ( Int ) [function, no-evaluators]

    rule X ==Int f(X) => false [simplification]
    rule f(X) ==Int X => false [simplification]
endmodule

module TEST-SPEC
    imports TEST

    claim <k> run(SetItem(X) |Set SetItem(f(X))) => done(SetItem(X) SetItem(f(X))) ... </k>

endmodule
```

I've looked at equation debug logs and such, and can't seem to find that it's applying equations in an infinite loop. Rather, it seems to get stuck in evaluateCondition or something.

I've attached a bug report. 
[kore-exec.tar.gz](https://github.com/kframework/kore/files/7637285/kore-exec.tar.gz)

### PR DESCRIPTION
**Pull request by ana-pantilie**
Fixes #2928

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by denis-bogdanas** [comment]
What is the status of this PR? I guess it is prerequisite for https://github.com/runtimeverification/k/issues/2612

**Comment by ana-pantilie** [comment]
@denis-bogdanas This PR is blocked on https://github.com/runtimeverification/k/issues/2612.

**Comment by denis-bogdanas** [comment]
@ana-pantilie note that this PR acts as if the following rule is implemented internally:
```
rule S -Set .Set  => S [simplification]
```
Please check.

**Comment by denis-bogdanas** [comment]
@ana-pantilie I finished symbolic rules implementation in https://github.com/runtimeverification/k/pull/2689 . That PR is not compatible with master K version of Haskell. Only with this PR. A fix to Haskell must be implemented first.

**Review by jberthold — APPROVED** [review]
LGTM :)

**Pull request merged**
