### PR TITLE
Fixing HLint execution on runners due to missing libtinfo5 dependency

### PR DESCRIPTION
**Pull request by F-WRunTime**

### CODE REVIEW

**Comment by F-WRunTime** [comment]
Per issues found in this PR by @treeowl 
https://github.com/runtimeverification/haskell-backend/pull/3396 

Installation on public runner of library enables execution of Hlint

**Comment by treeowl** [comment]
It's hard to know what to think of this unless/until integration tests can run. HLint was only the least important symptom.

**Review by treeowl — APPROVED** [review]
FWIW, I also approve if CI passes.

**Comment by treeowl** [comment]
Question: should we just stop requiring M1 (apparently experimental, and currently down) and macos12 (generally sluggish) tests to run before triggering the integration and perf tests?

**Comment by treeowl** [comment]
Unfortunately, it seems there's more left to fix here. 😕

**Comment by goodlyrottenapple** [comment]
closing in favour of #3401, since the underlying issue with the cachix action on ubuntu-22.04 https://github.com/cachix/cachix-action/issues/130 is currently unsolved.

**Comment by F-WRunTime** [comment]
> 

This PR lacks the other additional changes as it was to also update and sync the checkout versions. Please add that to your PR or open this.

**Pull request closed without merging**
