### PR TITLE
Clean up nix CI and add GHC9 build

### PR DESCRIPTION
**Pull request by goodlyrottenapple**
Merged the two separate build and unit test workflows into one, as it seems pointless to run both separately. Also added a build of the kore-exec binary via GHC9 to make sure we keep all our deps in sync across both versions.

### CODE REVIEW

**Review by jberthold — COMMENTED** [review]
Makes sense to combine the builds. Maybe we can also test the `nix-shell`, as the last step in this combined job?
Our github settings seem to require the old jobs to succeed (as [status checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging)) ; we will have to get that removed by @F-WRunTime or @ehildenb

**Comment by ana-pantilie** [comment]
@F-WRunTime In order to merge this, we need to do the following:
1. remove merge rights from everyone (except admin)
2. merge this PR
3. update all PRs to be up to date with master
4. give merge rights back to everyone

**Comment by F-WRunTime** [comment]
> * remove status checks from required

@ana-pantilie I can also Merge without waiting for requirements to be merged? Based on what you're asking for I believe that meets the need here as well no? I can go ahead and just merge it and go through PRs to update the branches. 
Give me the go ahead and will begin to execute. Please ping me on slack if you do not get a response from me within a day. Thank you.

**Comment by F-WRunTime** [comment]
Talked with Sam and will proceed.

**Review by jberthold — APPROVED** [review]
LGTM, thanks for restoring the `nix-shell` check

**Pull request merged**
