### PR TITLE
[#3111] Bypass `hookedSymbols` lookup

### PR DESCRIPTION
**Pull request by dcastro**
# Work in progress!

Fixes part of #3111

### Scope:

Problem: In `lookupAxiomSimplifier`, if the axiom identifier for the
given term is an `Axiom.Identifier.Application`, we look for the hook
inside the `hookedSymbols` map.

However, in some cases, the term itself might already carry a hook. If
that's the case, then we don't need to perform a lookup in the
`hookedSymbols` map.

See this comment for context:
https://github.com/runtimeverification/haskell-backend/pull/3184#discussion_r938637613

Solution: check if the term carries a hook first, and only do a lookup
in `hookedSymbols` if it doesn't.

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [x] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [x] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [x] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [x] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by dcastro** [comment]
@goodlyrottenapple: It appears the test "key outside of map, symbolic opaque terms" in `Test.Kore.Unification.Unifier` is now failing (all other tests, including integration tests, are passing).

In this test, `lookupAxiomSimplifier` is called with a term such that:
* `matchAxiomIdentifier` returns an `Application` with id `"concatMap"`
* `getHookFromTermLike` returns the hook `"MAP.concat"`

Previously, we'd look up "concatMap" in `hookedSymbols`. This lookup would fail (because `Mock.env.hookedSymbols` is an empty map), and `lookupAxiomSimplifier` would return `Nothing`.

After the changes in this PR, we match the "MAP.concat" hook with the builtin evaluator `Kore.Builtin.Map.evalConcat`, and return it in a `Just`.

----

Is the test's expectation wrong (and therefore needs to be updated), or is this a legit use-case that this PR breaks?

**Comment by goodlyrottenapple** [comment]
> Is the test's expectation wrong (and therefore needs to be updated), or is this a legit use-case that this PR breaks?

I am not sure as still fairly new to the codebase. @ana-pantilie would know. Given the name of the test, perhaps we just want to make a copy of `Mock.concatMap` which has a dummy hook instead?

**Comment by ana-pantilie** [comment]
@dcastro I think the test's output was actually subtly wrong because of what you said, so feel free to update it with the current result! Thanks.

**Comment by breakerzirconia** [comment]
The actual result of the only failing test case `Test.Kore.Unification.Unifier.test_unification: "key outside of map, symbolic opaque terms"` now expects the [Type](https://github.com/runtimeverification/haskell-backend/blob/diogo/%233111-bypass-map-lookup/kore/src/Kore/Attribute/Pattern/Simplified.hs#L67) of [constr20](https://github.com/runtimeverification/haskell-backend/blob/diogo/%233111-bypass-map-lookup/kore/test/Test/Kore/Unification/Unifier.hs#L657) to be `Fully` instead of `Partly`, meaning these changes invalidate the `Simplified` attribute.

**Pull request closed without merging**
