### PR TITLE
use state to cache simplifier across branches during unification

### PR DESCRIPTION
**Pull request by dwightguth**
### Scope:

We introduce a `StateT` monad transformer to the monad used by `unificationProcedure` so that multiple calls to simplify the same term across multiple different branches of unification are cached and do not have to reinvoke the simplifier each time.

It is possible that this will introduce some overhead due to the cost of hashing and comparing equality on the terms. Do not merge until I've had a chance to do performance testing.

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by dwightguth** [comment]
Performance measurements show that this removes the bottleneck on my example by taking it from running over half an hour without finishing to finishing in under 4 minutes.

I also ran some KEVM proofs and found that it doesn't affect them that much, but certainly there's no significant adverse performance impact on any of them.

Here is the difference in seconds between the old and new times on the proofs I ran:

```
-3.936 4.676 -0.296 tests/specs/benchmarks/address00-spec.k
-5.262 -8.277 -0.221 tests/specs/benchmarks/bytes00-spec.k
-4.61 8.581 -7.455 tests/specs/benchmarks/ecrecover00-siginvalid-spec.k
-11.294 -12.621 0.184 tests/specs/benchmarks/ecrecover00-sigvalid-spec.k
-8.524 -8.939 2.346 tests/specs/benchmarks/encode-keccak00-spec.k
-8.608 -10.172 -1.336 tests/specs/benchmarks/encodepacked-keccak01-spec.k
-2.808 -3.708 -1.305 tests/specs/benchmarks/functional-spec.k
-2.535 -2.856 -1.111 tests/specs/benchmarks/keccak00-spec.k
-1.674 -0.845 -0.415 tests/specs/benchmarks/overflow00-nooverflow-spec.k
-1.687 -3.602 0.289 tests/specs/benchmarks/overflow00-overflow-spec.k
-2.876 0.029 0.069 tests/specs/benchmarks/requires01-a0gt0-spec.k
2.04 -0.732 0.481 tests/specs/benchmarks/requires01-a0le0-spec.k
-4.095 -5.077 0.519 tests/specs/benchmarks/staticarray00-spec.k
-5.563 -1.185 -1.573 tests/specs/benchmarks/staticloop00-a0lt10-spec.k
0.692 3.676 0.449 tests/specs/benchmarks/storagevar00-spec.k
-1.563 -4.504 -0.51 tests/specs/benchmarks/storagevar01-spec.k
0.427 -3.705 1.019 tests/specs/benchmarks/storagevar02-nooverflow-spec.k
-2.759 -1.058 -0.134 tests/specs/benchmarks/storagevar02-overflow-spec.k
1.795 4.108 0.049 tests/specs/benchmarks/storagevar03-spec.k
1.023 6.309 -0.08 tests/specs/functional/infinite-gas-spec.k
0.023 0.018 0.006 tests/specs/functional/lemmas-no-smt-spec.k
0.064 3.977 -0.11 tests/specs/functional/lemmas-spec.k
0.957 9.252 -0.096 tests/specs/functional/merkle-spec.k
0.549 2.458 0.353 tests/specs/functional/storageRoot-spec.k
```

First column is wall time, second is user time, third is system time. Looking specifically at wall time, we see that the slowest was an increase in 2 seconds and the fastest was a reduction in 11 seconds. Most of them were either faster or only minutely slower. I believe these are acceptable performance numbers, given that the possible increase in time is well within the margin for error u

**Comment by dwightguth** [comment]
in all

**Review by jberthold — APPROVED** [review]
LGTM

**Review by ana-pantilie — APPROVED** [review]
Nice!

**Pull request merged**
