### PR TITLE
Make make tail recursive

### PR DESCRIPTION
**Pull request by treeowl**
`make` would recursively pattern match on the result of recursive computations. That's not great if there are many of them, so stop doin that. The modified code is also arguably easier to read.

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by treeowl** [comment]
I just realized this could be bad for performance if `MultiOrTop` is pretty common; in that case it's better to wait and see if the `Set` will be needed until the end, rather than building it eagerly. Does anyone know?

**Comment by goodlyrottenapple** [comment]
I made changes to MultiOr last and it was somewhat tricky to get right. From what I remember it is called fairly often? I suggest you profile a run with your change vs master and look at the profiles. I found using speedscope useful for seeing the calls to make.

**Comment by treeowl** [comment]
Here's the basic performance report.
[perf-rep.pdf](https://github.com/runtimeverification/haskell-backend/files/10171414/perf-rep.pdf).
I'll add profiling when I can.

**Comment by ana-pantilie** [comment]
Differences are indeed negligible, I think we can just merge this.

**Review by ana-pantilie — APPROVED** [review]

**Pull request merged**
