### PR TITLE
Df/caching termlike hashes

### PR DESCRIPTION
**Pull request by treeowl**
Cache the hash of the TermLikeF in the TermLike, and extract it in the Hashable instance instead of recursing into the TermLikeF.

The precomputed hash in produced using the derived Hashable instance of TermLikeF, which will call hash on the respective sub-structure (like And, Or, ...), wrapped into one of the TermLikeF constructors. For all such sub-structures, the derived Hashable instance will then recurse into the contents (containing a TermLike again for the case of TermLike), thereby using the cached hashes directly instead of performing a deep recursion.

Partially addresses https://github.com/runtimeverification/haskell-backend/issues/3113

Fixes #nnnn

### Estimate:

---

###### Review checklist

The author performs the actions on the checklist. The reviewer evaluates the work and checks the boxes as they are completed.

-   [ ] **Summary.** Write a summary of the changes. Explain what you did to fix the issue, and why you did it. Present the changes in a logical order. Instead of writing a summary in the pull request, you may push a clean Git history.
-   [ ] **Documentation.** Write documentation for new functions. Update documentation for functions that changed, or complete documentation where it is missing.
-   [ ] **Tests.** Write unit tests for every change. Write the unit tests that were missing before the changes. Include any examples from the reported issue as integration tests.
-   [ ] **Clean up.** The changes are already clean. Clean up anything near the changes that you noticed while working. This does not mean only spatially near the changes, but logically near: any code that interacts with the changes!

### CODE REVIEW

**Comment by jberthold** [comment]
* to fix the `Update/Style` issues: look at what `nix run .#format` (or run `scripts/fourmolu.sh` if you have `fourmolu` installed)
* for the failing integration test where the ordering of outputs changed, you can create a new "golden" output file using 
```
$ cd test/regression-c
$ make golden
```
This re-creates the one `*.out.golden` file that is checked after running the shell script.

**Comment by jberthold** [comment]
See https://github.com/runtimeverification/haskell-backend/issues/3303 for an example how to trigger a profiling run with a tarball (this tarball is from #3286)

**Comment by treeowl** [comment]
The KEVM test suggests I lack adequate permissions.

**Comment by jberthold** [comment]
> The KEVM test suggests I lack adequate permissions.

That's a gotcha in the github settings - you need to be _publicly_ a member of the RV organosation, i.e. [make your membership publicly visible](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership). 
The `/KEVM-perf-run` might still not work properly at the moment, though - unfortunately there is a problem that I was unable to track down.

**Comment by treeowl** [comment]
[Profiling? Maybe?](https://github.com/runtimeverification/haskell-backend/files/9670919/kevm-bug-storagevar03-with-conditions.tar.gz)

**Comment by treeowl** [comment]
Looks promising! It would be good to see what happens with the stricter versions.

**Comment by jberthold** [comment]
indeed...worth a try. These are the top consumers now, still have `hashWithSalt1` but _a lot_ better than before.

 COST CENTRE                  | MODULE                                 | %time | %alloc | SRC                                                          |
------------------------------|----------------------------------------|-------|--------|--------------------------------------------------------------|
 ravel                        | Data.Generics.Internal.VL.Lens         |   1.8 |    1.6 | src/Data/Generics/Internal/VL/Lens.hs:66:1-42                |
 simplifySubstitutionWorker   | Kore.Simplify.SubstitutionSimplifier   |   1.6 |    1.9 | src/Kore/Simplify/SubstitutionSimplifier.hs:(267,1)-(399,78) |
 compare                      | Data.InternedText                      |   1.6 |    0.0 | src/Data/InternedText.hs:(82,5)-(86,61)                      |
 guardAgainstBottom           | Kore.TopBottom                         |   1.5 |    0.8 | src/Kore/TopBottom.hs:45:1-49                                |
 unionWith                    | Data.Map.Strict.Internal               |   1.5 |    0.9 | src/Data/Map/Strict/Internal.hs:(990,1)-(996,35)             |
 fmap                         | Kore.Internal.Predicate                |   1.4 |    0.3 | src/Kore/Internal/Predicate.hs:171:21-27                     |
 compare                      | Kore.Rewrite.RewritingVariable         |   1.3 |    0.0 | src/Kore/Rewrite/RewritingVariable.hs:75:25-27               |
 addConditionWithReplacements | Kore.Internal.SideCondition            |   1.3 |    1.1 | src/Kore/Internal/SideCondition.hs:(310,1)-(333,29)          |
 liftSimplifier               | Kore.Simplify.Simplify                 |   1.3 |    2.0 | src/Kore/Simplify/Simplify.hs:192:5-42                       |
 second                       | Data.Generics.Internal.Profunctor.Lens |   1.2 |    3.1 | src/Data/Generics/Internal/Profunctor/Lens.hs:(72,1)-(73,53) |
 repIso                       | Data.Generics.Internal.Profunctor.Iso  |   1.2 |    2.7 | src/Data/Generics/Internal/Profunctor/Iso.hs:38:1-20         |
 first                        | Data.Generics.Internal.Profunctor.Lens |   1.1 |    2.7 | src/Data/Generics/Internal/Profunctor/Lens.hs:(67,1)-(68,53) |
 substitute                   | Kore.Internal.TermLike.TermLike        |   1.1 |    1.6 | src/Kore/Internal/TermLike/TermLike.hs:(871,5)-(969,57)      |
 project                      | Kore.Internal.Predicate                |   1.1 |    4.3 | src/Kore/Internal/Predicate.hs:(325,5)-(327,67)              |
 hashWithSalt1                | Data.Hashable.Class                    |   1.1 |    0.2 | Data/Hashable/Class.hs:271:1-45                              |
 foldr                        | Kore.Internal.MultiAnd                 |   1.0 |    2.4 | src/Kore/Internal/MultiAnd.hs:80:36-43                       |
 simplify                     | Kore.Simplify.Predicate                |   1.0 |    1.1 | src/Kore/Simplify/Predicate.hs:(115,1)-(188,48)              |
 attemptEquation              | Kore.Equation.Application              |   1.0 |    1.1 | src/Kore/Equation/Application.hs:(125,1)-(216,38)            |
 pure                         | SMT                                    |   0.9 |    1.2 | src/SMT.hs:512:10-20                                         |
 insert                       | Data.Set.Internal                      |   0.6 |    1.2 | src/Data/Set/Internal.hs:(532,1)-(544,48)                    |
 matchWith                    | Kore.Variables.Binding                 |   0.5 |    1.3 | src/Kore/Variables/Binding.hs:(106,1)-(108,44)               |
 fmap                         | Kore.Syntax.Application                |   0.5 |    1.1 | src/Kore/Syntax/Application.hs:69:21-27                      |
 sendSExpr                    | SMT.AST                                |   0.5 |    1.8 | src/SMT/AST.hs:(196,1)-(207,22)                              |
 alex_scan_tkn                | Kore.Parser.Lexer                      |   0.5 |    1.4 | dist/build/Kore/Parser/Lexer.hs:(891,1)-(924,67)             |
 hPutStr                      | Data.Text.IO                           |   0.4 |    1.3 | src/Data/Text/IO.hs:(182,1)-(193,56)                         |
 balanceR                     | Data.Map.Internal                      |   0.3 |    1.2 | src/Data/Map/Internal.hs:(4139,1)-(4158,50)                  |
 alexGetByte                  | Kore.Parser.Lexer                      |   0.2 |    3.3 | src/Kore/Parser/Lexer.x:(264,1)-(273,35)                     |
 verifySort                   | Kore.Validate.SortVerifier             |   0.2 |    1.1 | src/Kore/Validate/SortVerifier.hs:(29,1)-(62,27)             |

**Review by goodlyrottenapple — APPROVED** [review]

**Comment by jberthold** [comment]
@treeowl ^^^ we have an `automerge` bot that reads this label and merges master into PR branches that are ready (i.e., does more than github's auto-merge - it also  has some degree of work queue management to avoid build storms).

**Review by jberthold — APPROVED** [review]

**Review by ana-pantilie — APPROVED** [review]

**Pull request merged**
