### PR TITLE
Adjusting default timeout

### PR DESCRIPTION
**Pull request by PetarMax**
The PR sets the default timout to a large value, which is consistent with the requirements of Kontrol engagement proofs.

### CODE REVIEW

**Comment by geo2a** [comment]
Why not set this value as default at the Kontrol level?

**Comment by geo2a** [comment]
In a Slack conversation, Petar has pointed out that the default timeout of 125 ms is unconditionally used to check the SMT prelude. That was not enough with some custom options passed to z3 via `--smt-option`.

We should use the user-specified timeout when checking the prelude.

**Comment by goodlyrottenapple** [comment]
> In a Slack conversation, Petar has pointed out that the default timeout of 125 ms is unconditionally used to check the SMT prelude. That was not enough with some custom options passed to z3 via `--smt-option`.
> 
> We should use the user-specified timeout when checking the prelude.

Will open a quick PR, as this is something I noticed last week whilst refactoring the SMT code and was going to address in a separate PR

**Comment by goodlyrottenapple** [comment]
closing in favour of #4030

**Pull request closed without merging**
